# Generated by Django 3.0.7 on 2020-06-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(help_text='Enter Your First Name', max_length=100)),
                ('person_name', models.CharField(help_text='Second Person First Name', max_length=100)),
            ],
        ),
    ]
